#!/usr/bin/env python3
from pyrogram import Client,  filters
import re,random,os,requests,ownutils,io,sys
from asyncio import sleep
testmode=0
app = Client(
    "my_account",
    plugins=dict(root="plugins")
    )
app.run()
