#!/usr/bin/env python3
from pyrogram import Client,filters
app = Client(
    "my_account",
    plugins=dict(root="plugins")
    )

@app.on_message(filters.command("test", prefixes="%") & filters.me)
async def test(client, message):
    await message.edit_text("Works good")


@app.on_message(filters.command("restart", prefixes="%") & filters.me)
async def reboot(client, message):
    import os
    import sys
    await message.edit_text("Restarting")
    os.execl(sys.executable, sys.executable, *sys.argv)


@app.on_message(filters.command("insmod", prefixes="%") & filters.me)
async def downloadmodule(client, message):
    args = message.text.split(" ")
    import os
    import requests
    import pickle
    if args[1] == "usage":
        await message.edit_text("Usage:\n%insmod {module url} {OPTIONAL:module name}\nModule class:core\nDescription:download and install modules. TODO: depedency resolving")
    elif len(args) > 3:
        await message.edit_text("Please, choose ONE module name.")
    elif len(args) < 2:
        await message.edit_text("I need link for download")
    else:
        if len(args) == 2 :
            link=args[1].split("/")
            name=link[len(link)-1]
        else:
            name=args[2]+".py"
        try:
            os.chdir("plugins")
        except FileNotFoundError:
            os.mkdir("plugins")
            os.chdir("plugins")
        with open(f"{name}", "w") as modfile:
            r = requests.get(args[1])
            fc = r.content.decode("UTF-8")
            modfile.write(fc)
            await message.edit_text(f"Module {name} installed")
        os.chdir("../")


app.run()
